// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLxil9NKjaVQ2xPr_e15bd7kHuv0Ws5g',
    appId: '1:348806189603:web:c0494148a554602ab61796',
    messagingSenderId: '348806189603',
    projectId: 'erjigit-5271f',
    authDomain: 'erjigit-5271f.firebaseapp.com',
    storageBucket: 'erjigit-5271f.appspot.com',
    measurementId: 'G-HX4T63PY5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAizzz6TjmU8xDIUSGBCBkYqa6x-9O90l8',
    appId: '1:348806189603:android:77767596bd7f703db61796',
    messagingSenderId: '348806189603',
    projectId: 'erjigit-5271f',
    storageBucket: 'erjigit-5271f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11seJhIbXijpb7VBOmUbGvKBbVsLY2SQ',
    appId: '1:348806189603:ios:4223a01dbbd0c769b61796',
    messagingSenderId: '348806189603',
    projectId: 'erjigit-5271f',
    storageBucket: 'erjigit-5271f.appspot.com',
    iosClientId: '348806189603-mebme160ipub7kchjfpqk71959me1pqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11seJhIbXijpb7VBOmUbGvKBbVsLY2SQ',
    appId: '1:348806189603:ios:4223a01dbbd0c769b61796',
    messagingSenderId: '348806189603',
    projectId: 'erjigit-5271f',
    storageBucket: 'erjigit-5271f.appspot.com',
    iosClientId: '348806189603-mebme160ipub7kchjfpqk71959me1pqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaApp',
  );
}
